default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>
  host: localhost
  username: postgres
  password: newpassword

development:
  <<: *default
  database: salon_app_back_end_development

test:
  <<: *default
  database: super

nirmal:
  <<: *default
  database: salon_app_back_end_development

production:
  <<: *default
  database: salon_app_back_end_production
  username: postgres
  password: newpassword
