default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>
  host: localhost
  username: postgres
  password: newpassword

development:
  <<: *default
  database: salon_app_back_end_development
  username: <%= ENV['SALON_APP_BACKEND_DATABASE_USER'] %>
  password: <%= ENV['SALON_APP_BACKEND_DATABASE_PASSWORD'] %>
  host: <%= ENV['SALON_APP_BACKEND_DATABASE_HOSTNAME'] %>
  port: 5432

test:
  <<: *default
  database: salon_app_back_end_test
  username: <%= ENV['SALON_APP_BACKEND_DATABASE_USER'] %>
  password: <%= ENV['SALON_APP_BACKEND_DATABASE_PASSWORD'] %>
  host: <%= ENV['SALON_APP_BACKEND_DATABASE_HOSTNAME'] %>
  port: 5432

nirmal:
  <<: *default
  database: salon_app_back_end_development

production:
  <<: *default
  database: salon_app_back_end_production
  username: postgres
  password: newpassword
